# broad: 크롤링 검색용 / longtail: 초안 소제목 힌트용
KEYWORDS = [
    # ── 성과관리 ──────────────────────────────────────────────────────────────
    {"keyword": "성과관리", "category": "성과관리", "language": "KO", "track": "broad"},
    {"keyword": "성과관리 트렌드", "category": "성과관리", "language": "KO", "track": "broad"},
    {"keyword": "성과관리 시스템", "category": "성과관리", "language": "KO", "track": "broad"},
    {"keyword": "지속적 성과관리", "category": "성과관리", "language": "KO", "track": "broad"},
    {"keyword": "성과관리 사례", "category": "성과관리", "language": "KO", "track": "broad"},
    {"keyword": "performance management", "category": "성과관리", "language": "EN", "track": "broad"},
    {"keyword": "performance management trends", "category": "성과관리", "language": "EN", "track": "broad"},
    {"keyword": "performance management system", "category": "성과관리", "language": "EN", "track": "broad"},
    {"keyword": "continuous performance management", "category": "성과관리", "language": "EN", "track": "broad"},
    {"keyword": "performance management examples", "category": "성과관리", "language": "EN", "track": "broad"},
    {"keyword": "성과관리 시스템 구축 방법", "category": "성과관리", "language": "KO", "track": "longtail"},
    {"keyword": "스타트업 성과관리", "category": "성과관리", "language": "KO", "track": "longtail"},
    {"keyword": "성과관리 도입 사례", "category": "성과관리", "language": "KO", "track": "longtail"},
    {"keyword": "성과관리 KPI 설정 방법", "category": "성과관리", "language": "KO", "track": "longtail"},
    {"keyword": "성과관리 보상 연계", "category": "성과관리", "language": "KO", "track": "longtail"},
    {"keyword": "how to build performance management system", "category": "성과관리", "language": "EN", "track": "longtail"},
    {"keyword": "performance management for startups", "category": "성과관리", "language": "EN", "track": "longtail"},
    {"keyword": "performance management case studies", "category": "성과관리", "language": "EN", "track": "longtail"},
    {"keyword": "agile performance management", "category": "성과관리", "language": "EN", "track": "longtail"},
    {"keyword": "performance management software comparison", "category": "성과관리", "language": "EN", "track": "longtail"},
    # ── 성과평가 ──────────────────────────────────────────────────────────────
    {"keyword": "성과평가", "category": "성과평가", "language": "KO", "track": "broad"},
    {"keyword": "자기평가", "category": "성과평가", "language": "KO", "track": "broad"},
    {"keyword": "연말평가", "category": "성과평가", "language": "KO", "track": "broad"},
    {"keyword": "다면평가", "category": "성과평가", "language": "KO", "track": "broad"},
    {"keyword": "평가 면담", "category": "성과평가", "language": "KO", "track": "broad"},
    {"keyword": "performance review", "category": "성과평가", "language": "EN", "track": "broad"},
    {"keyword": "self review", "category": "성과평가", "language": "EN", "track": "broad"},
    {"keyword": "year-end review", "category": "성과평가", "language": "EN", "track": "broad"},
    {"keyword": "360 degree review", "category": "성과평가", "language": "EN", "track": "broad"},
    {"keyword": "performance review meeting", "category": "성과평가", "language": "EN", "track": "broad"},
    {"keyword": "성과평가 예시", "category": "성과평가", "language": "KO", "track": "longtail"},
    {"keyword": "성과평가 양식", "category": "성과평가", "language": "KO", "track": "longtail"},
    {"keyword": "성과평가 코멘트 작성법", "category": "성과평가", "language": "KO", "track": "longtail"},
    {"keyword": "자기평가 작성법", "category": "성과평가", "language": "KO", "track": "longtail"},
    {"keyword": "연말평가 준비 체크리스트", "category": "성과평가", "language": "KO", "track": "longtail"},
    {"keyword": "performance review phrases examples", "category": "성과평가", "language": "EN", "track": "longtail"},
    {"keyword": "performance review template", "category": "성과평가", "language": "EN", "track": "longtail"},
    {"keyword": "how to write a self review", "category": "성과평가", "language": "EN", "track": "longtail"},
    {"keyword": "year-end performance review checklist", "category": "성과평가", "language": "EN", "track": "longtail"},
    {"keyword": "performance review comments examples", "category": "성과평가", "language": "EN", "track": "longtail"},
    # ── 인사평가 ──────────────────────────────────────────────────────────────
    {"keyword": "인사평가", "category": "인사평가", "language": "KO", "track": "broad"},
    {"keyword": "인사평가 기준", "category": "인사평가", "language": "KO", "track": "broad"},
    {"keyword": "인사평가 등급", "category": "인사평가", "language": "KO", "track": "broad"},
    {"keyword": "인사고과", "category": "인사평가", "language": "KO", "track": "broad"},
    {"keyword": "인사평가 양식", "category": "인사평가", "language": "KO", "track": "broad"},
    {"keyword": "HR evaluation", "category": "인사평가", "language": "EN", "track": "broad"},
    {"keyword": "HR evaluation criteria", "category": "인사평가", "language": "EN", "track": "broad"},
    {"keyword": "HR evaluation rating", "category": "인사평가", "language": "EN", "track": "broad"},
    {"keyword": "performance appraisal", "category": "인사평가", "language": "EN", "track": "broad"},
    {"keyword": "HR evaluation form", "category": "인사평가", "language": "EN", "track": "broad"},
    {"keyword": "인사평가 기준 작성법", "category": "인사평가", "language": "KO", "track": "longtail"},
    {"keyword": "인사평가 등급 분포 사례", "category": "인사평가", "language": "KO", "track": "longtail"},
    {"keyword": "인사평가 면담 질문", "category": "인사평가", "language": "KO", "track": "longtail"},
    {"keyword": "인사평가 항목 예시", "category": "인사평가", "language": "KO", "track": "longtail"},
    {"keyword": "인사평가 결과 면담 방법", "category": "인사평가", "language": "KO", "track": "longtail"},
    {"keyword": "how to design HR evaluation criteria", "category": "인사평가", "language": "EN", "track": "longtail"},
    {"keyword": "HR evaluation rating distribution", "category": "인사평가", "language": "EN", "track": "longtail"},
    {"keyword": "HR performance appraisal questions", "category": "인사평가", "language": "EN", "track": "longtail"},
    {"keyword": "HR evaluation form template", "category": "인사평가", "language": "EN", "track": "longtail"},
    {"keyword": "HR evaluation feedback meeting", "category": "인사평가", "language": "EN", "track": "longtail"},
    # ── 리더십 진단 ───────────────────────────────────────────────────────────
    {"keyword": "리더십 진단", "category": "리더십 진단", "language": "KO", "track": "broad"},
    {"keyword": "리더십 평가", "category": "리더십 진단", "language": "KO", "track": "broad"},
    {"keyword": "리더십 역량 진단", "category": "리더십 진단", "language": "KO", "track": "broad"},
    {"keyword": "리더십 다면진단", "category": "리더십 진단", "language": "KO", "track": "broad"},
    {"keyword": "리더십 진단 도구", "category": "리더십 진단", "language": "KO", "track": "broad"},
    {"keyword": "leadership assessment", "category": "리더십 진단", "language": "EN", "track": "broad"},
    {"keyword": "leadership evaluation", "category": "리더십 진단", "language": "EN", "track": "broad"},
    {"keyword": "leadership competency assessment", "category": "리더십 진단", "language": "EN", "track": "broad"},
    {"keyword": "360 leadership feedback", "category": "리더십 진단", "language": "EN", "track": "broad"},
    {"keyword": "leadership assessment tool", "category": "리더십 진단", "language": "EN", "track": "broad"},
    {"keyword": "리더십 진단 설계 방법", "category": "리더십 진단", "language": "KO", "track": "longtail"},
    {"keyword": "리더십 진단 설문 문항", "category": "리더십 진단", "language": "KO", "track": "longtail"},
    {"keyword": "리더십 진단 결과 해석", "category": "리더십 진단", "language": "KO", "track": "longtail"},
    {"keyword": "리더십 진단 사례 분석", "category": "리더십 진단", "language": "KO", "track": "longtail"},
    {"keyword": "리더십 다면진단 운영 방법", "category": "리더십 진단", "language": "KO", "track": "longtail"},
    {"keyword": "leadership assessment design guide", "category": "리더십 진단", "language": "EN", "track": "longtail"},
    {"keyword": "leadership 360 feedback questionnaire", "category": "리더십 진단", "language": "EN", "track": "longtail"},
    {"keyword": "how to interpret leadership assessment results", "category": "리더십 진단", "language": "EN", "track": "longtail"},
    {"keyword": "leadership competency model examples", "category": "리더십 진단", "language": "EN", "track": "longtail"},
    {"keyword": "leadership assessment best practices", "category": "리더십 진단", "language": "EN", "track": "longtail"},
    # ── 조직 진단 ─────────────────────────────────────────────────────────────
    {"keyword": "조직 진단", "category": "조직 진단", "language": "KO", "track": "broad"},
    {"keyword": "조직문화 진단", "category": "조직 진단", "language": "KO", "track": "broad"},
    {"keyword": "조직 진단 도구", "category": "조직 진단", "language": "KO", "track": "broad"},
    {"keyword": "팀 건강진단", "category": "조직 진단", "language": "KO", "track": "broad"},
    {"keyword": "조직 효과성 진단", "category": "조직 진단", "language": "KO", "track": "broad"},
    {"keyword": "organization assessment", "category": "조직 진단", "language": "EN", "track": "broad"},
    {"keyword": "organizational culture assessment", "category": "조직 진단", "language": "EN", "track": "broad"},
    {"keyword": "organizational diagnostic tool", "category": "조직 진단", "language": "EN", "track": "broad"},
    {"keyword": "team health check", "category": "조직 진단", "language": "EN", "track": "broad"},
    {"keyword": "organizational effectiveness assessment", "category": "조직 진단", "language": "EN", "track": "broad"},
    {"keyword": "조직 진단 설문 문항", "category": "조직 진단", "language": "KO", "track": "longtail"},
    {"keyword": "조직문화 진단 방법", "category": "조직 진단", "language": "KO", "track": "longtail"},
    {"keyword": "조직 진단 결과 해석", "category": "조직 진단", "language": "KO", "track": "longtail"},
    {"keyword": "조직 효과성 측정 지표", "category": "조직 진단", "language": "KO", "track": "longtail"},
    {"keyword": "팀 건강진단 운영 사례", "category": "조직 진단", "language": "KO", "track": "longtail"},
    {"keyword": "organization assessment survey questions", "category": "조직 진단", "language": "EN", "track": "longtail"},
    {"keyword": "organizational culture assessment method", "category": "조직 진단", "language": "EN", "track": "longtail"},
    {"keyword": "how to interpret organization assessment results", "category": "조직 진단", "language": "EN", "track": "longtail"},
    {"keyword": "organizational effectiveness metrics", "category": "조직 진단", "language": "EN", "track": "longtail"},
    {"keyword": "team health check best practices", "category": "조직 진단", "language": "EN", "track": "longtail"},
]

BROAD_KEYWORDS = [k for k in KEYWORDS if k["track"] == "broad"]
